# -*- coding: utf-8 -*-
""" 🚩Практика diabet Отбор Признаков triu  roc_auc plt slice DF C Series mutual.ipynb


Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15bRbEVDsDFdyfHu7szPtrC8k1FzDL3eh

# START
"""

# !pip uninstall gdown -y && pip install gdown  # установка gdown
import os
os.getcwd()
from os import read
# from google.colab import drive  # авторизовались и заходим в google drive
from glob import glob
# drive.mount('/content/drive')  # открывает доступ  к файлам хранящимся на Google Drive

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import matplotlib.colors
import matplotlib.ticker as mtick

from sklearn.feature_selection import SelectKBest, mutual_info_classif, f_regression, f_classif, chi2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, roc_auc_score, mean_squared_error

from sklearn.metrics import confusion_matrix, RocCurveDisplay, classification_report
# from sklearn.metrics import confusion_matrix, classification_report

from mlxtend.feature_selection import SequentialFeatureSelector
from mlxtend.feature_selection import ExhaustiveFeatureSelector
from sklearn.feature_selection import RFE

"""#  Работа по определению заболевания Диабет --- ДА / НЕТ"""

df = pd.read_csv('D:\Eduson_data\diabetes_binary_5050split_health_indicators_BRFSS2015.csv')
df.head(10).T
df.info()

# Фильтрация ◾ отбор признаков
# * Экспертная оценка
# * Визуальная оценка
# * Статистическая оценка

#%%
print(df[df.duplicated()].columns, '\n')  # Имена столбцов с дубликатами
print(df[df.duplicated()].sum(), '\n')  # Количество до удаления

print('% Дубликатов относительно порядка/размера DF : ' , '\n', f'{df[df.duplicated()].sum() / (len(df) / 100)}', '\n')  # % Дубоикатов относительно порядка DF
print('1 Общий процент Дубликатов относительно порядка/размера DF : ', '\n', f'{100 / len(df) * df.duplicated().sum()}', '\n')
print('2 DF без дубликатов / на полный размер DF : ', '\n', f'{(len(df) - len(df.drop_duplicates()))/ len(df)}')

#%%
#  Создали константный признак

df['surprise'] = 5

df.describe().T

"""# Удаляем избыточный признак surprise"""

# df = df.drop(['surprise'], axis=1)
df.info()

"""# Изменить имя Series"""

# Через сохранение в переменную
df_rename = df.nunique()

df_rename.name = 'unique_samples'

print('Num unique samples : \n', df.nunique())

print(df_rename)

"""# Выделение переменных ◾ отбор категориальных, числовых

MY ◾ Некорректный 🚫
* `Python фильтрация` нежелательно, только` pandas код`
"""

target = df['Diabetes_binary']

dfu = df.nunique()

# 1️️
num_var = [column for column, unique in zip(dfu.index, dfu) if unique > 2]

# 2️⃣
# df.nunique() - это Series
num_var = df.nunique()[(df.nunique() > 2) & (target.name not in df.nunique().index)].index



# 1️️
bool_var = [column for column, unique in zip(df.nunique().index, df.nunique()) if unique == 2]
# 2️⃣
bool_var = [var for var in df.nunique().index if df.nunique()[var] == 2 and var != target.name]


print('num_var : \n', num_var, '\n')
print('bool_var : \n', bool_var, '\n')
print(df.CholCheck.value_counts())


"""# ◻ HERE ◾ Отбор бинарных признаков
* Pandas фильтрация
"""

# target = 'Diabetes_binary'


bool_var = df.nunique()[df.nunique() == 2].index.drop('Diabetes_binary')

# Методом исключения и списка bool_var
num_var = [i for i in df.columns if i not in bool_var and i != 'Diabetes_binary']

print(num_var, '\n')
print(bool_var)

"""#  normalize=True

* `value_counts(0)` — покажет `количество`.

* `value_counts(1)` — покажет `доли`.

#  .spines и .set_visible(False)
 * это настройка внешнего вида рамки графика
    * `.spines` -- Это границы (рамки) вокруг графика, и они представлены в виде словаря `{'top': Spine, 'bottom': Spine, 'left': Spine, 'right': Spin}`
    * `.spines[['top', 'right']] ` -- Это выбор конкретных рамок, например, верхней и правой.
    * `.set_visible(False)` -- Это метод, который отключает отображение этих рамок.

# 1️⃣Способ Eduson
# """

df['Diabetes_binary'].value_counts(1).plot(kind='barh',figsize=(10, 2),
                                           color='#53AEFF').spines[['top', 'right']].set_visible(True);
plt.title('Diabetes_binary Distribution (%)', fontsize=10)
plt.yticks(ticks=[0,1], labels=['Non-Diabetic', 'Diabetic']);
# plt.show()


"""2️⃣ Способ GPT - Правильно
* `ax.spines` --- `раздельно`
"""

ax = df['Diabetes_binary'].value_counts(1).plot(kind='barh', figsize=(10, 2), color='#FF851B')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
# plt.show()


"""# corrwith ◾ мера линейной связи признаков с целевой"""



# print(df.drop('Diabetes_binary', axis=1).columns)

(df.drop('Diabetes_binary', axis=1)  # DF без целевой
   .corrwith(target)
   .sort_values(ascending=False)
   .plot(kind='bar', figsize=(12, 4), title="Diabetes_binary Correlation", alpha=0.8, zorder=3, color='#2E8CE3')
   .spines[['top','right', 'left']].set_visible(False)
   )
plt.grid(axis='y', linestyle='--', alpha=.5)
plt.xticks(rotation=45, ha='right', size=10)
# plt.show()


# """# corrwith ◾ Корреляция DF с таргетом + сортировка
# `corrwith` --- `Степень линейной связи`, Корреляция DF с таргетом
# * `corrwith` - возвращает `Series`, поэтому соответствующие методы
# * `corr_df[corr_df[0] > 0.15]` - Задаём `порог кореляции`, для `отбора` признаков
# * `'corr_var'` --- имя колонки по моей инициативе
# """
#
# corr_df = pd.DataFrame(df.drop(target, axis=1).corrwith(df.Diabetes_binary), columns=['corr_var']).sort_values('corr_var', ascending=False)
# corr_df[abs(corr_df['corr_var']) > 0.15]
#
# """# correlation threshold ◾ порог кореляции
# 1️⃣ наибольшая абсолютная корреляция, предположим, по порогу 0.15
#
#
# """
#
# corr_df[abs(corr_df['corr_var'])>0.15]
#
# """2️⃣ признаки, у которых корреляция меньше порога"""
#
# corr_df[(abs(corr_df['corr_var'])<=0.15)]
#
# """# Корреляционная матрица признаков друг с другом
# * При линейной зависимостью кореляция будет высокой
# * `custom_cmap` ---  задаём цвеовую палитру для heatmap
# * `mask` ---  создаётся Маска кореляционной матрицы
# * `np.ones_like` --- создаётся `единичная` матрица по размерам исходной `data_heatmap.corr()`
# * `np.triu` --- из `np.ones_like` создаём треугольную верхнюю матрицу
#     * `dtype=bool` --- со значениями матрицы `True / False`
# * `annot=False` --- подписи клеточек
# """
#
# data_heatmap = df
# custom_cmap = mpl.colors.LinearSegmentedColormap.from_list('custom', ['#2E4CE3', '#FFDDC4', '#582E09'])
#
# mask = np.triu(np.ones_like(data_heatmap.corr(), dtype=bool))
#
# # Размеры heatmap
# lenghtsize = 30
# fig, ax = plt.subplots(figsize=(lenghtsize,lenghtsize*.35), dpi=200)
#
#
# heatmap = sns.heatmap(data_heatmap.corr(), cmap=custom_cmap, mask=mask, annot=True, vmin=-.8, vmax=.8)
# heatmap.set_title('Correlation Heatmap', fontdict={'fontsize':24}, pad=16);
# ax.tick_params(axis='both', which='major', labelsize=20)
# plt.setp(ax.xaxis.get_majorticklabels(), rotation=45, ha='right');
#
# """# ◻ ( X, у ) - для моделирования
#
# * Целевая
# """
#
# y = df['Diabetes_binary']
# X = df.drop(['Diabetes_binary'], axis=1)
#
# """# chi2 всего DF без Целевой
# * Красивое оформление:
#   * Результирующая Таблица Транспонирована
#   * Индексы Именованы Признаками
#   * Столбцы именованы параметрами chi2
#   * Сортировка по возрастанию
# """
#
# chisquare = pd.DataFrame(chi2(X, y)).T.set_index(X.columns).rename(
#                 columns={0:'chi2_score', 1:"chi2_pValue"}).sort_values(by='chi2_score', ascending=False)
#
# chisquare
#
# """# ✅ mutual_info_classif
#
#
# 1️⃣ - Только для `Дискретной` Целевой
#
# 2️⃣ - `Применим` для `cat_feat` и `num_feat`
#
# 3️⃣ - ловит `любые зависимости`
#
# ---
#
# # Взаимная информация ◾ mutual_info_classif ◾ Отлов Нелинейностей
# 🔥 Выявление скрытой `нелинейной` связи `признаков` с `целевой`
# * `mutual_info_classif(X, y)` --- оценивает `взаимную` информацию `между` каждым `признаком` в X и целевой `переменной y`.
#   * сколько `бит` (или `единиц` информации) `признак даёт` для предсказания целевой
#
# * Это `неметрический` аналог корреляции --- он оценивает `нелинейные зависимости` в `ненормированных` еденицах
#
# * Возвращает массив из `n_features` значений: для `каждого признака` — `сколько едениц` информации он `даёт` о `целевой переменной`.
#     * `Значения > 0` — признак `несёт` информацию о `Y`
#
#     * Значения `=`  `0` — признак `бесполезен`
#
#
#
# * Это абсолютная величина, и она зависит от:
#
#     * распределения данных
#
#     * количества классов
#
#     * плотности признаков
# """
#
# bool_vars = X.nunique()[X.nunique() == 2].index # Фильтр имён бинарных признаков
#
#
# mut_info = mutual_info_classif(X[bool_vars],y)  # Взаимная инф. Бинарных Признаков и Целевой
# mut_df = pd.DataFrame(mut_info, columns=['Mutual_info'], index=X[bool_vars].columns) # создание DF результатов c Взаимной инф.
# mut_df.sort_values(by='Mutual_info',ascending=False)
#
#
# mut_df
#
# import math
# round(len(X.nunique()[X.nunique() == 2]) * 100 / len(X.columns), ndigits=0)
# # [i for i in X.columns if X[i].unique().size == 2]
# # len(X.columns)
# # len(X.nunique()[X.nunique() == 2])
#
# X.NoDocbcCost.unique()
#
# """# ⭐◻ baseline ◾RandomForestClassifier
#
# ✅ Стандартизацию не делаем
#
# 1️⃣ ◻ `random_state` - начальное состояние генератора случайных чисел
# """
#
# r_state = 42
#
# """2️⃣ ◻ Модель Случайный Лес
#  с фиксированным random_state, rf_clf
# """
#
# rf_clf = RandomForestClassifier(random_state=r_state)
#
# """3️⃣ ◻ разделяем выборки train_test_split
#   * `stratify` -  позволяет сохранить исходное  распределение Целевой  в Обучающей и Тестовой выборках
# """
#
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=r_state, stratify=y)
#
# """4️⃣ обучение и предикт y_rf_0"""
#
# rf_clf.fit(X_train, y_train)
#
# y_rf_0 = rf_clf.predict(X_test)
#
# """5️⃣  roc-auc score
# * roc_auc_score = 0,73  -> это качество ранжирования
# * 🔥🔥 это оценка того что` умеет ли она отличать` класс `1` от класса `0` по `вероятностям` по` шкале от 0 до 1`
# * Эта метрика показывает --- насколько `хорошо` модель `ранжирует объекты` по степени `уверенности` в `положительном классе`.
#     * Положительный объект (positive class) — это объект, который относится к классу 1,
#     * Отрицательный объект (negative class) — это объект, который относится к классу 0.
#
#
# """
#
# roc_auc_score(y_rf_0, y_test)
#
# """6️⃣ classification_report
# * `precision` -- модель предсказала принадлежность классу `больше` чем есть, `перебор`
#   * `precision=0,7` --- 70% `положительных` предсказаний `правильно` а `положительных` предсказаний 30% нет
# * `recall`  -- модель предсказала принадлежность классу `меньше` чем есть, `недобор`
#   * `recall=0.75` --- 75% положительных объектов `предсказано правильно`, а 25% `пропущено`
# * `support` -- количество реальных объектов каждого класса в y_true
# * `f1-score` -- Показывает `баланс` между `точностью` и `полнотой`
# """
#
# print(classification_report(y_rf_0, y_test))
#
# X.columns
#
# """7️⃣ обучение и предикт `y_rf_1` `без признака` >>> `NoDocbcCost`
# * `NoDocbcCost` --- ✨ `Mutual_info` определил этот признак как `не влияющий` на `модель`
# * Удалив `NoDocbcCost` расчитываем на повышение качества
# """
#
# rf_clf.fit(X_train.drop(['NoDocbcCost'], axis=1), y_train)  # Обучение
#
# y_rf_1 = rf_clf.predict(X_test.drop(['NoDocbcCost'], axis=1))  #  Прогноз на Тестовой выборке
#
# """8️⃣ roc_auc_score
# * `roc_auc_score` почти `не изменился` , хотя признак `NoDocbcCost` мы считаем `неинформативным`
# """
#
# roc_auc_score(y_rf_1, y_test)
#
# """9️⃣ classification_report"""
#
# print(classification_report(y_rf_1, y_test))
#
# X.groupby(X['NoDocbcCost']).count()
#
# """# slice DF"""
#
# z = X['NoDocbcCost'].value_counts()
# y = X['NoDocbcCost']
#
# print('\n', z[1], '\n')
#
# print(X.loc[2:5, 'HighBP'	: 'Stroke'], '\n')
#
# y.groupby(level=0).sum() == 1
#
# """GPT ◾ Внутренний Баланс Бинарных Признаков"""
#
# import pandas as pd
#
# # Пример: пусть у нас есть DataFrame df
# # Задаём порог: если частота самого частого значения > 99%, считаем признак "почти постоянным"
# threshold = 0.95
#
# # Сохраняем признаки, у которых максимум по value_counts превышает порог
# low_variance_cols = []
#
# for col in X.columns:
#     top_freq = X[col].value_counts(normalize=True, dropna=False).max()
#     if top_freq > threshold:
#         low_variance_cols.append((col, top_freq))
#
# # Выводим признаки с их частотами
# for col, freq in low_variance_cols:
#     print(f"{col}: частота самого частого значения = {freq:.2%}")
#
# """# Внутренний Баланс Бинарных Признаков ◾ По порогу
# * Считаем максимальную частоту одного из бинаров
# * фильтруем признаки с частотой бинара > 70%
# """
#
# treshold = 0.75
# for i in X.columns:
#   if len(X[i].value_counts()) == 2:
#     freq = X[i].value_counts(normalize=True, dropna=False).max()
#     if freq <= treshold:
#       print(freq)
#
# """# 🔥 roc_auc_score ◾ SVM ◾ LogisticRegression ◾ f1_score
#
# * `y_pred = clf.predict(X_test) ` - `y_pred` содержит только `0` и `1`
#
#   * `roc_auc_score` - задумывался как метрика `качества ранжирования` , если на входе `0` и `1` то ранжира нет
#
# * `f1_score`  - работает только с бинарами
#
# * 👍 `roc_auc_score`(`y_test`, `y_score`) считаем по `y_score`, где `y_score` — это:
#
#   * Для `LogisticRegression` ➡➡ `predict_proba(X)[:, 1]` — вероятность принадлежности к классу `1`
#
#   * Для `SVM` ➡➡ `decision_function(X)` — оценка уверенности (`distance to hyperplane`)
#
# * 🎈 Для `SVM`  то же можно использовать `predict_proba(X)[:, 1]`, но в параметрах надо указать `SVC(probability=True)`
#
# # Автоматизация проверки roc_auc_score ◾ predict_proba
# * 🔥 При `поочерёдном` удалении признаков
# * `predict_proba(...)[:, 1]` ---	Предсказываем вероятности (`score`) класса 1 (но не метки), для `последующего` использования в  `roc_auc_score` .
#     * `[:, 1]` — это срез по NumPy-массиву
#
#
# * Так как `predict_proba` возвращает `2-х мерный` массив вероятностей, мы выводим `вероятность` `положительного` `класса 1`
#     * `1` - `положительный` класс, с положительными объектами
#     * `0` - `отрицательный` класс, с отрицательными объектами
#
# ```
# predict_proba - возвращает вероятности 1-го и 0-го класса
#
# [[0.93, 0.07],  ← первая строка: 7% вероятности болезни, где 0.93 класс 0 / 0.07 класс 1
#  [0.21, 0.79],  ← вторая строка: 79% вероятности болезни, где 0.21 класс 0 / 0.79 класс 1
#  [0.56, 0.44],  ← и т.д.
#  ...]
# ```
# """
#
# # Базовое качество модели на всех признаках (без удаления)
# base_score = roc_auc_score(y_test, rf_clf.predict_proba(X_test)[:, 1])
#
# # Поочерёдно исключаем каждый признак
# for feature in X.columns:
#     X_train_drop = X_train.drop(columns=[feature])
#     X_test_drop = X_test.drop(columns=[feature])
#
#     # Обучаем модель без этого признака
#     rf_clf.fit(X_train_drop, y_train)
#
#     # Предсказываем вероятности положительного класса
#     y_pred = rf_clf.predict_proba(X_test_drop)[:, 1]
#
#     # Считаем AUC на тестовой выборке
#     score = roc_auc_score(y_test, y_pred)
#
#     # Печатаем результат: имя признака, новый AUC и разницу с базой
#     print(f'{feature:25} | ROC AUC: {score:.4f} | Δ: {score - base_score:.4f}')
#
# """# ⭐ embedded ◾ Встроенные методы отбора данных ◾ LogisticRegression
#
# ✅ Стандартизация обязательно
#
# 1️⃣
#
# `fit_transform(X_train)`:
#
#   * Сначала вычисляет `среднее` и `стандартное отклонение` по `X_train` (fit),
#
#   * Потом `применяет` масштабирование (`transform`).
#
# `transform(X_test)`:
#
#   * Просто `применяет` уже `вычисленные параметры` (mean и std) из `X_train`,
#
#   * `Использует` их для `масштабирования` X_test.
#
# ```
# # Выбран кодовый формат
# ```
# """
#
# scaler = StandardScaler()
#
# X_train_sc = scaler.fit_transform(X_train) # Обучили StandardScaler на train
# X_test_sc = scaler.transform(X_test)  # Применяем масштабирование, обученное на тренировочной выборке
#
# """2️⃣  Классификатор
#  * `penalty='l1'` --- регуляризация L1 коэфф. `линейно-корелированные` признаки и `слабые` признаки `Зануляет`
#  * `C=0.01`  --- обратная сила регуляризации:
#   * Чем `меньше` C, тем `сильнее` регуляризация `(больше штраф)`.
#   * Чем больше C, тем меньше регуляризация.
#   * в данном случае `C=0.01` — это `сильная регуляризация`, много весов может стать 0
#  * `solver='liblinear'` --- метод оптимизации
#   * Это алгоритм, который решает уравнение логистической регрессии.
#
#
# * Поддерживает `penalty='l1'`
#
# * Хорош для `небольших` и `средних` датасетов
#
# * При использованиии `penalty='l2'`, можно было бы использовать `'lbfgs'`, 'saga' `Встроенный код` и другие.
#
# ☝ ☝ создаём объект модели логистической регрессии с определёнными параметрами
# """
#
# lr_clf = LogisticRegression(penalty='l1', C=0.01, solver='liblinear')
#
# """3️⃣ обучаем на шкалированных данных"""
#
# lr_clf.fit(X_train_sc, y_train)
#
# '''
# Эхо
# '''
# # LogisticRegression(C=0.01, penalty='l1', solver='liblinear')
#
# """▶ Коэффициенты после обучения"""
#
# lr_clf.coef_[0]
#
# """4️⃣ Предсказываем"""
#
# y_lr_0 = lr_clf.predict(X_test_sc)
#
# """5️⃣ roc_auc_score"""
#
# roc_auc_score(y_lr_0, y_test)
#
# """6️⃣ classification_report"""
#
# print(classification_report(y_lr_0, y_test))
#
# """7️⃣ смотрим коэффициенты признаков
#
# * `lr_clf.coef_` --- Это массив коэффициентов (весов) при признаках.
#
# * `lr_clf.coef_` — это 2D-массив, потому что в общем случае может быть много классов (например, для `многоклассовой классификации`).
#
# * Для бинарной классификации (0 и 1) — это массив размером (1, n_features).
#
# 👍 👍 Красивый вывод расчитанных моделью коффициентов
# * Некоторые коэффю L1 обнулила поэтому эти признаки можно удалить
# """
#
# coef_df = pd.DataFrame(zip(X_train.columns, np.transpose(lr_clf.coef_[0])), columns=['features', 'coef'])
# coef_df
#
# """8️⃣  `feature importance` по мнению ✨ `случайного леса`
# *
# """
#
# rf_clf.fit(X_train, y_train)
#
# y_predict = rf_clf.predict(X_test)
#
# """9️⃣ ✨  `feature_importances_` --- используем для `случайного леса` потому что нет `встроенных` методов `отбора признаков`"""
#
# rf_clf.feature_importances_
#
# """🔟 `feature_importances_ `  --- красивый вывод"""
#
# pd.DataFrame(zip(X_train.columns, rf_clf.feature_importances_), columns=['feature', 'importance']
#             ).sort_values(by='importance', ascending=False)
#
# """# ⭐ Обёртки
# * потому что `аргументом` методов является `обученная модель`
# * Последовательный перебор
# * Полный перебор
# """
#
# efs = ExhaustiveFeatureSelector(model, min_features=1, max_features=3, scoring='accuracy', cv=5)
# sfs = SequentialFeatureSelector(model, k_features=3, forward=True, scoring='r2', cv=5)
#
# """# ❇ Прямой отбор
# Начинаем с `пустого` набора признаков:
#
# На каждом шаге:
#
# * Пробуем добавить по `одному признаку` из оставшихся.
#
# * Оцениваем качество модели (например, по `roc_auc_score`, `accuracy`, `f1` и т.п.).
#
# * Выбираем `наиболее` `полезный признак` и добавляем его в `текущий набор`.
#
# * Повторяем, пока:
#
#   * модель `улучшается` (или `не ухудшается`);
#
#   * или достигнут `лимит` признаков (`k_features`).
#
# 🔸 Это `жадный метод` — он не гарантирует глобально лучший набор, `но быстро` даёт `хороший` результат.
# """
#
# forw_feature = SequentialFeatureSelector(lr_clf, k_features='best', forward = True, n_jobs=-1)
# forw_feature.fit(X_train, y_train)
#
# """Выводим наиболее полезные признаки
#
# * `estimator =	lr_clf` ---	Модель, с которой происходит отбор (логистическая регрессия в твоём случае)
# * `k_features =	'best'`	Автоматически подбирается наилучшее количество признаков (по метрике)
# * `forward =	True`	 --- Прямой отбор, добавляем признаки, начиная с пустого набора
# * `n_jobs =	-1`	--- Параллелизация, использовать все доступные ядра
# """
#
# features = list(forw_feature.k_feature_names_)
# features
#
# """# ❇ Последовательный отбор
#
# 1️⃣ строим модель на полном наборе `центрированных` признаков `X_train_sc`
# """
#
# lr_clf.fit(X_train_sc, y_train)
#
# bfs = SequentialFeatureSelector(lr_clf, k_features='best', forward = False, n_jobs=-1)
#
# """2️⃣ Обучаем"""
#
# bfs.fit(X_train_sc, y_train)
#
# """3️⃣ StandardScaler возвращает  `X_train_sc` это тип `numpy.ndarray` , поэтому имён признаков нет только № столбцов
# * `k_feature_names_` — это `номера` столбцов `ndarray`
# """
#
# features = list(bfs.k_feature_names_)
#
# # Проверим тип возвращённых данных
# print(list(map(type, features)))
# features
#
# """4️⃣ `HERE` Красивый ваывод отобранных признаков
#
# """
#
# # HERE
# for i in range(len(features)):
#   print(X_train.columns.tolist()[int(features[i])])
#
# """5️⃣ MY"""
#
# # MY
# res = [X_train.columns[int(i)] for i in features]
# res
#
# """6️⃣7️⃣ `GPT ` Красивый ваывод отобранных признаков
#
# 💥 `bfs.k_feature_idx_` — это кортеж целых чисел - `индексов` (надежнее для обращения к колонкам DataFrame),
# """
#
# for feat in bfs.k_feature_idx_:
#     print(X_train.columns[feat])